# Generated by Django 2.0.8 on 2018-10-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=20)),
                ('costo', models.FloatField()),
                ('img_url', models.ImageField(blank=True, upload_to='')),
                ('estado', models.IntegerField()),
            ],
        ),
    ]
