# Generated by Django 2.1.2 on 2018-10-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_sesion_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalles_personales',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='detalles_personales',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
