# Generated by Django 2.1.2 on 2018-10-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_auto_20181016_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, verbose_name='Tamaño')),
            ],
        ),
    ]
