# Generated by Django 2.1.2 on 2018-10-25 21:16

from django.db import migrations

def crearTamanos(apps, schema_editor):
	modelo = apps.get_model('rest', 'Tamano')

	pequeno = modelo()
	pequeno.nombre = "PEQUEÑO"
	pequeno.save()

	mediano = modelo()
	mediano.nombre = "MEDIANO"
	mediano.save()

	grande = modelo()
	grande.nombre = "GRANDE"
	grande.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0007_tamano'),
    ]

    operations = [
    	migrations.RunPython(crearTamanos),
    ]
