# Generated by Django 2.1.2 on 2018-10-25 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_auto_20181025_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamano_Borde',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('borde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Borde')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Tamano')),
            ],
        ),
        migrations.CreateModel(
            name='Tamano_Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Componente')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Tamano')),
            ],
        ),
        migrations.CreateModel(
            name='Tamano_Masa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.FloatField()),
                ('masa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Masa')),
                ('tamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Tamano')),
            ],
        ),
    ]
