# Generated by Django 2.1.2 on 2018-10-31 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0010_auto_20181030_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combos_promocionales',
            name='fecha_fin',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='combos_promocionales',
            name='fecha_inicio',
            field=models.DateField(blank=True),
        ),
    ]
