# Generated by Django 2.1.2 on 2018-11-12 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_auto_20181112_0519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tamano_ingrediente',
            name='porcion',
        ),
        migrations.AddField(
            model_name='pizza_tamano_ingrediente',
            name='porcion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.Porcion'),
        ),
    ]
