# Generated by Django 2.1.2 on 2018-11-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0012_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='costo',
            field=models.FloatField(default=0.0),
        ),
    ]
