# Generated by Django 2.1.2 on 2018-11-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_promocion_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='costo',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
