# Generated by Django 2.1.2 on 2018-12-11 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0014_direccion_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Favorita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Pizza')),
            ],
        ),
    ]
