# Generated by Django 2.1.2 on 2018-12-14 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0015_pizza_favorita'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza_favorita',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
