# Generated by Django 2.1.2 on 2018-11-08 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_auto_20181108_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='borde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Tamano_Borde'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='masa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Tamano_Masa'),
        ),
    ]
