# Generated by Django 2.1.2 on 2018-12-17 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0016_pizza_favorita_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='costo',
        ),
    ]
