# Generated by Django 2.1.2 on 2018-11-08 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0017_auto_20181108_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza_Tamano_Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='pizza',
            name='tamano',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='pizza_tamano_ingrediente',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Pizza'),
        ),
        migrations.AddField(
            model_name='pizza_tamano_ingrediente',
            name='tamano_ingrediente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Tamano_Ingrediente'),
        ),
    ]
