# Generated by Django 2.1.2 on 2018-11-12 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0019_porcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='tamano',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.Tamano'),
        ),
    ]
