# Generated by Django 2.1.2 on 2019-01-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0020_auto_20190103_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
