# Generated by Django 2.1.2 on 2019-01-17 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0026_auto_20190117_0320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordenada_Poligono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenada', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.Coordenada')),
            ],
        ),
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.Local')),
            ],
        ),
        migrations.AddField(
            model_name='coordenada_poligono',
            name='poligono',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.Poligono'),
        ),
    ]
