# Generated by Django 2.1.2 on 2019-01-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0029_auto_20190117_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='poligono',
            name='color',
            field=models.CharField(default='#4286f4', max_length=10),
        ),
    ]
