# Generated by Django 2.1.2 on 2019-02-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0033_auto_20190206_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
