# Generated by Django 2.1.2 on 2019-02-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0034_auto_20190207_0719'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entregado',
            field=models.IntegerField(default=0),
        ),
    ]
