# Generated by Django 2.1.2 on 2019-02-07 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0036_pedido_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Local'),
        ),
    ]
