# Generated by Django 2.1.2 on 2019-02-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0038_combinacion_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='recibido',
            field=models.IntegerField(default=0),
        ),
    ]
