# Generated by Django 2.1.2 on 2019-02-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0039_pedido_recibido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
