# Generated by Django 2.1.2 on 2019-02-08 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0040_auto_20190208_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='coordenada_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.Coordenada'),
        ),
    ]
