# Generated by Django 2.1.2 on 2018-10-16 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_auto_20181016_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='token',
            field=models.CharField(max_length=70),
        ),
    ]
