# Generated by Django 2.1.2 on 2018-12-05 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0013_auto_20181112_0538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion_Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Dirección', max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('latitud', models.CharField(max_length=15)),
                ('longitud', models.CharField(max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
