# Generated by Django 2.1.2 on 2019-01-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0021_coordenada'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalles_personales',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
