# Generated by Django 2.1.2 on 2019-01-08 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0022_detalles_personales_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('horario_atencion', models.TextField()),
                ('estado', models.BooleanField()),
                ('coordenada', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest.Coordenada')),
            ],
        ),
    ]
