# Generated by Django 2.1.2 on 2019-01-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0023_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='local',
            old_name='nombre',
            new_name='sector',
        ),
        migrations.RemoveField(
            model_name='local',
            name='horario_atencion',
        ),
        migrations.AddField(
            model_name='local',
            name='apertura',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='local',
            name='cierre',
            field=models.TimeField(default=None),
        ),
        migrations.AddField(
            model_name='local',
            name='ciudad',
            field=models.CharField(default='Guayaquil', max_length=64),
        ),
    ]
